{{- $global := . }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- range $processType, $processInfo := .Values.processes }}
---
apiVersion: {{ template "chartty.capabilities.deployment.apiVersion" $global }}
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}-{{ $processType }}
  labels:
    process_type: {{ $processType }}
    {{- include "chartty.labels" $global | nindent 4 }}
spec:
  replicas: {{ $processInfo.replicas | default $.Values.replicaCount }}
  selector:
    matchLabels:
      process_type: {{ $processType }}
      {{- include "chartty.selectorLabels" $global | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        process_type: {{ $processType }}
        {{- include "chartty.labels" $global | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- include "chartty.imagePullSecretNames" $global | nindent 8 }}
      serviceAccountName: {{ include "chartty.serviceAccountName" $global }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      {{- with $.Values.global.hostAliases }}
      hostAliases:
        {{- toYaml $.Values.global.hostAliases | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $.Chart.Name }}-{{ $processType }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: {{ include "chartty.image" $global }}
          {{- if hasKey $processInfo "command" }}
          command: 
          {{- range $idx, $value := $processInfo.command }}
            - "{{ $value }}"
          {{- end }}
          {{- end }}
          {{- if hasKey $processInfo "args" }}
          args:
          {{- range $idx, $value := $processInfo.args }}
            - "{{ $value }}"
          {{- end }}
          {{- end }}
          {{- with $.Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ $.Values.global.image.pullPolicy }}
          env:
            {{- include "chartty.envs" $global | nindent 12 }}
          {{- with $.Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12}}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ $.Values.httpPort }}
              protocol: TCP
          {{- with $processInfo.resources }}
          resources:
            {{- toYaml $processInfo.resources | nindent 12 }}
          {{- end }}
          {{- with $processInfo.readinessProbe }}
          readinessProbe:
              {{- toYaml . | nindent 14 }} 
          {{- end }}
          {{- with $processInfo.livenessProbe }}
          livenessProbe:
              {{- toYaml . | nindent 14 }} 
          {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
