{{- $global := . }}
{{- $chart_version := .Chart.Version | replace "+" "_" }}
{{- range $name, $hook := .Values.preRunHooks }}
{{- if $hook.enabled }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ $.Chart.Name }}-{{ $name }}
  labels:
    {{- include "chartty.labels" $global | nindent 4 }}
  annotations:
    "helm.sh/hook": {{ default "pre-upgrade,pre-install" $hook.position }}
    "helm.sh/hook-weight": "{{ $hook.weight }}"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  imagePullSecrets:
    {{- include "chartty.imagePullSecretNames" $global  | nindent 4 }}
  restartPolicy: OnFailure
  {{- with $.Values.volumes }}
  volumes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $.Values.global.hostAliases }}
  hostAliases:
    {{- toYaml $.Values.global.hostAliases | nindent 4 }}
  {{- end }}
  containers:
    - name: {{ $.Release.Name }}-{{ $name }}
      image: {{ include "chartty.image" $global }}
      imagePullPolicy: {{ $.Values.global.image.pullPolicy }}
      env:
        {{- include "chartty.envs" $global | nindent 8 }}
      {{- with $.Values.envFrom }}
      envFrom:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      command:
        {{- toYaml $hook.command | nindent 8 }}
      args:
        {{- toYaml $hook.args | nindent 8 }}
      {{- with $.Values.volumeMounts }}
      volumeMounts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}

